letsencrypt-nginx:
  tty: true
  image: nginx:alpine
  restart: always
  stdin_open: true
  expose:
    - "80"
  volumes:
    - letsencrypt-verify:/usr/share/nginx/html/
  labels:
    io.rancher.sidekicks: rancher-lets-encrypt
    com.danieldent.rancher-nginx-active-lb.acme-host: True

rancher-lets-encrypt:
  tty: true
  image: $CI_REGISTRY_IMAGE:sha-$CI_BUILD_REF
  restart: always
  stdin_open: true
  env_file:
    - letsencrypt.env
  volumes:
    - letsencrypt-verify:/var/www/
    - letsencrypt-certs:/etc/letsencrypt/
  labels:
    # if we add the container as a rancher agent, we get magical things like Rancher server URL, and access keys for F-R-E-E!
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
